### ISSUE TITLE
Crash/Assert thrown by GetStakeReport v0.19.19

### ISSUE THREAD

**Issue by tawmaz** [pocketnetteam/pocketnet.core#86]
I have found an intermittent crash of pocketcoind which occurs when calling the API GetStakeReport.  When attaching a debugger it appears and assert is failing in AssertLockHeldInternal. 

Stack:

```
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f26a5830859 in __GI_abort () at abort.c:79
#2  0x00005572d05fcc38 in AssertLockHeldInternal (pszName=pszName@entry=0x5572d0fef568 "cs_main", 
    pszFile=pszFile@entry=0x5572d1077601 "wallet/wallet.cpp", nLine=nLine@entry=4317, cs=0x5572d12c5380 <cs_main>) at sync.cpp:161
#3  0x00005572d0bd2b6b in CMerkleTx::GetDepthInMainChain (this=0x5572d2bff740) at wallet/wallet.cpp:4317
#4  CMerkleTx::GetDepthInMainChain (this=this@entry=0x5572d2bff740) at wallet/wallet.cpp:4312
#5  0x00005572d0bac7ec in GetsStakeSubTotal (aRange=std::vector of length 35, capacity 64 = {...}) at wallet/rpcwallet.cpp:4114
#6  0x00005572d0bb0694 in getstakereport (request=...) at wallet/rpcwallet.cpp:4238
#7  0x00005572d098a7dc in CRPCTable::execute (this=0x5572d12d3860 <tableRPC>, request=...) at rpc/server.cpp:510
#8  0x00005572d0b74276 in HTTPReq (req=0x7f2654030970, rpcAuthenticate=<optimized out>) at httprpc.cpp:220
#9  0x00005572d0b75179 in std::function<bool (HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (
    __args#1="", __args#0=<optimized out>, this=0x7f2654005890) at /usr/include/c++/9/bits/std_function.h:683
#10 HTTPWorkItem::operator() (this=0x7f2654005860) at httpserver.cpp:58
#11 WorkQueue<HTTPClosure>::Run (this=0x5572d2bf4370) at httpserver.cpp:137
#12 HTTPWorkQueueRun (queue=0x5572d2bf4370) at httpserver.cpp:386
#13 0x00007f26a5c3dde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007f26a5d52609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007f26a592d293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by pocketnetteam** [comment]
Is it repeating itself? Are there any instructions for playback?

**Comment by tawmaz** [comment]
I have not observed it since.  As I recall it was an issue on nodes which were in process of syncing but not yet staking.
